### ISSUE TITLE
Python 2.7 compatibility

### ISSUE THREAD

**Issue by ioull** [elric91/ZiGate#10]
It seems that it is only compatible with python 3.

I made a change that seems to make it working with python 2.7 but I'm not 100% sure of my modification as I'm not an exert and didn't test it in python 3.0 

  import six
  def zigate_decode(data):
        encoded = False
        decoded_data = bytearray(b'')
        for x in six.iterbytes(data):
            if x == 0x02:
                encoded = True
            elif encoded is True:
                encoded = False
                decoded_data.append( x ^ 0x10 )
            else:
                decoded_data.append(x)
        return decoded_data

I'm now able to read my sensor value . Thanks for your job !

**Comment by elric91** [comment]
Thanks !
We focus on python3 for the time being as we still have plenty of functions to implement. 
Keep us informed if it is working properly for you with this minor modification, we may create a dedicated 2.7 branch if you feel ready to handle a bit of maintenance / tests / non regression

**Comment by ioull** [comment]
Sorry I'm not able to warranty the code working on 2.7 ... as I'm not a python developper and just tried to make it working for my need without any warranty, it's the raison why I did'nt provide you a pull request bit just an issue ;-) 
I just change my usage and use it now in python 3 so I can use your library as is.

**Comment by elric91** [comment]
So, problem solved in a way ... I'll close the issue. Will reopen if someone else express the need for it.
