### ISSUE TITLE
Debug output not available

### ISSUE THREAD

**Issue by nobodyman1** [elric91/ZiGate#13]
I followed your description and I was able to put the ZiGate into join mode but there is no debug output (as shown in your **Session Example**).
```
from threaded_serial import *
from pyzigate.interface import *
z = ZiGate()
conn = ThreadedConnection(z)
z.send_data('0049', 'FFFCFE00')
```
Do I have to enable the output somewhere?

I found out how to get some debug data:
```
import logging
logging.basicConfig(level=logging.INFO)
logging.getLogger('pyzigate')
```

**Comment by elric91** [comment]
Did you try examples ?
(I need to rewrite session example as it does not reflect last evolutions)
especially this part : 

```
l = logging.getLogger('zigate')
l.setLevel(logging.DEBUG)
l.addHandler(logging.StreamHandler())
```

**Comment by nobodyman1** [comment]
Yes, I tried your example ```threaded_serial.py``` which is included in the example folder! What parts do I have to fix to get it working?

**Comment by elric91** [comment]
do just run "/usr/bin/python3 threaded_serial.py" after installing the package through pypi or do you do something else ?

**Comment by nobodyman1** [comment]
No. I used ```pip3 install pyzigate``` to install the package.
Then I followed your example and started ```ipython3```.
Because ```conn = ThreadedConnection(z)``` gives an error I downloaded ```threaded_serial.py``` and used commands which I mentioned in my first comment.
Your example seems to give me the possibility to interact with the zigate.
If I use ```/usr/bin/python3 threaded_serial.py``` I get debug data, but how do I send data?

**Comment by elric91** [comment]
OK, so following your 1st post, should be in ipython3 : 

```
import logging
from threaded_serial import ThreadedConnection
from pyzigate.interface import ZiGate

l = logging.getLogger('zigate')
l.setLevel(logging.DEBUG)
l.addHandler(logging.StreamHandler())

z = ZiGate()
conn = ThreadedConnection(z)
z.send_data('0049', 'FFFCFE00')
```

My zigate is currently busy on my another machine so can't test right now, but that should work :
- verbose log is printed @ debug level
- to see the log in console, you need to plug it on StreamHandler
- logging is done on "zigate", not "pyzigate"

If it works, I'll update the README right away

**Comment by nobodyman1** [comment]
Great. Works perfectly. Thanks a lot!
