### ISSUE TITLE
Ikea Trådfri commands

### ISSUE THREAD

**Issue by ISO-B** [elric91/ZiGate#4]
This is just note. This is not an issue.
# Change bulb state:
Command: `0092`
Message: `'02' + short_address + '0101' + state`
Parameters: 
- short_address `device short address`
 - state:
   - Off: `00`
   - On: `01`
   - Toggle: `02`
	
# Change brightness:
Command: `0081`
Message: `'02' + short_address + '0101' + onoff + level + time`
Parameters:
- short_address `target device short address`
- onoff:
  - On: `01` (Turns bulb on if its off)
  - Might be possible to change brightness while bulb is off
- level:
  - Brightness level between `00` - `FF` / 0 - 256
  - Level `00` turns bulb Off
- time:
  - How long transition takes. `0000` - `FFFF` / 0 - 65535

# Change color temperature:
Command: `00C0`
Message: `'02' + short_address + '0101' + temperature + time`
Parameters:
- short_address `target device short address`
- temperature:
  - This is real color temperature. Lamp has 256 different steps.
  - Temperature between `0100` - `0200` / 256 - 512 = 256
- time:
  - How long transition takes. `0000` - `FFFF` / 0 - 65535
  
# Examples:
short_address = 6E8E

	OFF:    zigate.send_data('0092', '026E8E010100')
	ON:     zigate.send_data('0092', '026E8E010101')
	Toggle: zigate.send_data('0092', '026E8E010102')
	
	Brightness to min instant: zigate.send_data('0081', '026E8E010101010000')
	Brightness to min fade:    zigate.send_data('0081', '026E8E010101010010')
	Brightness to max instant: zigate.send_data('0081', '026E8E010101FF0000')
	Brightness to max fade:    zigate.send_data('0081', '026E8E010101FF0010')
	Brightness to 50% instant: zigate.send_data('0081', '026E8E010101800000')
	Brightness to 50% fade:    zigate.send_data('0081', '026E8E010101800010')

	Color to cold white: zigate.send_data('00C0', '026E8E010101000000')
	Color to warm white: zigate.send_data('00C0', '026E8E010102000000')
	Color to middle:     zigate.send_data('00C0', '026E8E010101800000')

**Comment by elric91** [comment]
Opened the wiki and created a page for this information in it
